export interface Energy {
  id: number;
  name: string;
  nameEn: string;
  arcana: string;
  planet: string;
  planetEn: string;
  keywords: string[];
  keywordsEn: string[];
  positive: string;
  positiveEn: string;
  negative: string;
  negativeEn: string;
  advice: string;
  adviceEn: string;
  slug: string;
}

export const ENERGIES: Energy[] = [
  { id: 1, name: 'Маг', nameEn: 'The Magician', arcana: 'The Magician', planet: 'Меркурій', planetEn: 'Mercury', keywords: ['воля','майстерність','ініціатива'], keywordsEn: ['willpower','mastery','initiative'], positive: 'Лідерство, впевненість, здатність досягати цілей. Люди з енергією Мага наділені природним лідерством і здатністю перетворювати ідеї на реальність. Вони мають сильну волю та харизму, що притягує інших.', positiveEn: 'Leadership, confidence, ability to achieve goals', negative: 'Маніпуляції, егоїзм, хитрість. У негативному прояві Маг може використовувати свої таланти для маніпуляцій, стати егоїстичним і хитрим.', negativeEn: 'Manipulation, egoism, cunning', advice: 'Розвивайте свої таланти та використовуйте силу волі для досягнення цілей. Навчіться спрямовувати свою енергію на користь не лише собі, а й оточуючим.', adviceEn: 'Develop your talents and use willpower to achieve your goals', slug: 'chyslo-1' },
  { id: 2, name: 'Жриця', nameEn: 'The High Priestess', arcana: 'The High Priestess', planet: 'Місяць', planetEn: 'Moon', keywords: ['інтуїція','мудрість','таємниця'], keywordsEn: ['intuition','wisdom','mystery'], positive: 'Глибока інтуїція, мудрість, чутливість. Жриця дарує тонке відчуття світу, здатність бачити приховане і розуміти людей без слів. Це енергія глибинної жіночої мудрості.', positiveEn: 'Deep intuition, wisdom, sensitivity', negative: 'Замкненість, пасивність, відірваність від реальності. У негативному прояві людина може йти у себе, уникати дій і жити в ілюзіях.', negativeEn: 'Withdrawal, passivity', advice: 'Довіряйте своїй інтуїції та розвивайте внутрішню мудрість. Знаходьте баланс між внутрішнім світом і зовнішніми діями.', adviceEn: 'Trust your intuition and cultivate inner wisdom', slug: 'chyslo-2' },
  { id: 3, name: 'Імператриця', nameEn: 'The Empress', arcana: 'The Empress', planet: 'Венера', planetEn: 'Venus', keywords: ['творчість','достаток','краса'], keywordsEn: ['creativity','abundance','beauty'], positive: 'Творчість, материнство, достаток, гармонія. Імператриця наповнює життя красою, достатком і теплотою. Це енергія створення, плідності та любові до життя.', positiveEn: 'Creativity, nurturing, abundance, harmony', negative: 'Лінь, залежність від комфорту, надмірна потурання. У негативному прояві людина може стати лінивою і залежною від матеріальних благ.', negativeEn: 'Laziness, dependence on comfort', advice: 'Розкривайте свій творчий потенціал та створюйте красу навколо себе. Вчіться давати і отримувати в гармонії.', adviceEn: 'Unlock your creative potential and create beauty around you', slug: 'chyslo-3' },
  { id: 4, name: 'Імператор', nameEn: 'The Emperor', arcana: 'The Emperor', planet: 'Марс', planetEn: 'Mars', keywords: ['влада','структура','стабільність'], keywordsEn: ['authority','structure','stability'], positive: 'Стабільність, відповідальність, організованість. Імператор будує, структурує і захищає. Це енергія порядку, авторитету та здатності тримати все під контролем.', positiveEn: 'Stability, responsibility, organization', negative: 'Тиранія, жорсткість, контроль. У негативному прояві Імператор стає тираном, надмірно контролює і не дає свободи ані собі, ані іншим.', negativeEn: 'Tyranny, rigidity, control', advice: 'Будуйте структуру та порядок у житті, беріть відповідальність. Але пам\'ятайте про гнучкість і тепло у стосунках.', adviceEn: 'Build structure and order in your life, take responsibility', slug: 'chyslo-4' },
  { id: 5, name: 'Ієрофант', nameEn: 'The Hierophant', arcana: 'The Hierophant', planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['вчитель','традиції','духовність'], keywordsEn: ['teacher','tradition','spirituality'], positive: 'Мудрість, наставництво, духовний розвиток. Ієрофант — природний вчитель і наставник. Він передає знання, зберігає традиції та веде інших до духовного зростання.', positiveEn: 'Wisdom, mentorship, spiritual growth', negative: 'Догматизм, моралізаторство, фанатизм. У негативному прояві людина може стати занадто жорсткою у своїх переконаннях і нетерпимою до інших поглядів.', negativeEn: 'Dogmatism, moralizing', advice: 'Шукайте знання та діліться мудрістю з іншими. Будьте відкритими до різних шляхів пізнання.', adviceEn: 'Seek knowledge and share wisdom with others', slug: 'chyslo-5' },
  { id: 6, name: 'Закохані', nameEn: 'The Lovers', arcana: 'The Lovers', planet: 'Венера', planetEn: 'Venus', keywords: ['любов','вибір','гармонія'], keywordsEn: ['love','choice','harmony'], positive: 'Любов, гармонія у стосунках, правильний вибір. Закохані — це енергія глибокого єднання, щирої любові та вміння робити правильний вибір серцем.', positiveEn: 'Love, harmony in relationships, right choice', negative: 'Нерішучість, залежність, трикутники. У негативному прояві людина може бути нерішучою, потрапляти в емоційну залежність від інших.', negativeEn: 'Indecisiveness, dependency', advice: 'Приймайте рішення серцем, будуйте гармонійні стосунки. Вчіться любити вільно, без залежності.', adviceEn: 'Make decisions with your heart, build harmonious relationships', slug: 'chyslo-6' },
  { id: 7, name: 'Колісниця', nameEn: 'The Chariot', arcana: 'The Chariot', planet: 'Марс', planetEn: 'Mars', keywords: ['перемога','рух','амбіції'], keywordsEn: ['victory','movement','ambition'], positive: 'Перемога, рух вперед, сила волі, успіх. Колісниця — це невпинний рух до мети, подолання перешкод і тріумф через наполегливість.', positiveEn: 'Victory, moving forward, willpower, success', negative: 'Агресія, нетерпіння, авторитарність. У негативному прояві людина стає занадто агресивною і нетерплячою.', negativeEn: 'Aggression, impatience', advice: 'Рухайтесь до мети з рішучістю, контролюйте свої імпульси. Перемога приходить до тих, хто не зупиняється.', adviceEn: 'Move toward your goal with determination, control your impulses', slug: 'chyslo-7' },
  { id: 8, name: 'Справедливість', nameEn: 'Justice', arcana: 'Justice', planet: 'Сатурн', planetEn: 'Saturn', keywords: ['баланс','карма','закон'], keywordsEn: ['balance','karma','law'], positive: 'Справедливість, баланс, чесність. Ця енергія дає сильне відчуття правди і справедливості, вміння зважувати рішення та нести відповідальність.', positiveEn: 'Justice, balance, honesty', negative: 'Осудливість, надмірна критичність, холодність. У негативному прояві людина стає занадто суворою суддею себе та інших.', negativeEn: 'Judgmentalism, excessive criticism', advice: 'Дотримуйтесь балансу та будьте чесні з собою і іншими. Пам\'ятайте: справедливість починається з себе.', adviceEn: 'Maintain balance and be honest with yourself and others', slug: 'chyslo-8' },
  { id: 9, name: 'Відлюдник', nameEn: 'The Hermit', arcana: 'The Hermit', planet: 'Нептун', planetEn: 'Neptune', keywords: ['самопізнання','мудрість','самотність'], keywordsEn: ['self-discovery','wisdom','solitude'], positive: 'Глибоке самопізнання, мудрість, духовний пошук. Відлюдник шукає істину всередині себе, це глибока аналітична натура з потужною інтуїцією.', positiveEn: 'Deep self-discovery, wisdom, spiritual quest', negative: 'Ізоляція, відчуженість, замкненість. У негативному прояві людина може ізолюватися від світу і замикатися в собі.', negativeEn: 'Isolation, alienation', advice: 'Знаходьте час для самопізнання та внутрішнього розвитку. Але не забувайте повертатися у світ і ділитися своєю мудрістю.', adviceEn: 'Find time for self-discovery and inner growth', slug: 'chyslo-9' },
  { id: 10, name: 'Колесо Фортуни', nameEn: 'Wheel of Fortune', arcana: 'Wheel of Fortune', planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['доля','цикли','удача'], keywordsEn: ['destiny','cycles','luck'], positive: 'Удача, нові можливості, позитивні зміни. Колесо Фортуни приносить зміни, нові цикли та можливості. Людям з цією енергією часто "щастить".', positiveEn: 'Luck, new opportunities, positive changes', negative: 'Непостійність, фаталізм, залежність від удачі. У негативному прояві людина може покладатися тільки на щастя і не прикладати зусиль.', negativeEn: 'Instability, fatalism', advice: 'Приймайте зміни як частину життя та використовуйте можливості. Вчіться бачити закономірності у циклах долі.', adviceEn: 'Embrace change as part of life and seize opportunities', slug: 'chyslo-10' },
  { id: 11, name: 'Сила', nameEn: 'Strength', arcana: 'Strength', planet: 'Сонце', planetEn: 'Sun', keywords: ['мужність','терпіння','внутрішня сила'], keywordsEn: ['courage','patience','inner strength'], positive: 'Внутрішня сила, мужність, терпіння, стійкість. Сила — це не груба фізична міць, а глибинна внутрішня потужність, здатність перемагати через любов і терпіння.', positiveEn: 'Inner strength, courage, patience, resilience', negative: 'Слабкість, страхи, агресія. У негативному прояві людина або пригнічує свою силу, або, навпаки, виявляє її через агресію.', negativeEn: 'Weakness, fears', advice: 'Розвивайте внутрішню силу та мужність через терпіння. Справжня сила — у м\'якості та любові.', adviceEn: 'Develop inner strength and courage through patience', slug: 'chyslo-11' },
  { id: 12, name: 'Повішений', nameEn: 'The Hanged Man', arcana: 'The Hanged Man', planet: 'Нептун', planetEn: 'Neptune', keywords: ['жертва','пауза','новий погляд'], keywordsEn: ['sacrifice','pause','new perspective'], positive: 'Нові перспективи, жертовність, духовне переродження. Повішений бачить світ з іншого кута, це дар бачити те, чого не бачать інші.', positiveEn: 'New perspectives, sacrifice, spiritual rebirth', negative: 'Застій, пасивність, жертовний комплекс. У негативному прояві людина може застрягти в бездіяльності або грати роль вічної жертви.', negativeEn: 'Stagnation, passivity', advice: 'Іноді потрібно зупинитися щоб побачити нові можливості. Змініть кут зору — і рішення прийде.', adviceEn: 'Sometimes you need to pause to see new possibilities', slug: 'chyslo-12' },
  { id: 13, name: 'Смерть', nameEn: 'Death', arcana: 'Death', planet: 'Плутон', planetEn: 'Pluto', keywords: ['трансформація','завершення','оновлення'], keywordsEn: ['transformation','endings','renewal'], positive: 'Трансформація, оновлення, звільнення від старого. Смерть у Матриці Долі — це не кінець, а потужна сила оновлення та трансформації.', positiveEn: 'Transformation, renewal, release from the old', negative: 'Страх змін, болісні закінчення, опір трансформації. У негативному прояві людина чіпляється за старе і боїться будь-яких змін.', negativeEn: 'Fear of change, painful endings', advice: 'Приймайте завершення як початок нового етапу. Кожна "смерть" старого відкриває двері для нового.', adviceEn: 'Accept endings as the beginning of a new chapter', slug: 'chyslo-13' },
  { id: 14, name: 'Помірність', nameEn: 'Temperance', arcana: 'Temperance', planet: 'Сатурн', planetEn: 'Saturn', keywords: ['гармонія','терпіння','баланс'], keywordsEn: ['harmony','patience','balance'], positive: 'Гармонія, помірність, терпіння, баланс. Помірність — це мистецтво золотої середини, вміння знаходити баланс у всьому.', positiveEn: 'Harmony, temperance, patience, balance', negative: 'Надмірна стриманість, нерішучість, нудьга. У негативному прояві людина може стати занадто обережною і втратити смак до життя.', negativeEn: 'Excessive restraint', advice: 'Знаходьте золоту середину та будьте терплячі. Баланс — ключ до гармонійного життя.', adviceEn: 'Find the golden mean and be patient', slug: 'chyslo-14' },
  { id: 15, name: 'Диявол', nameEn: 'The Devil', arcana: 'The Devil', planet: 'Сатурн', planetEn: 'Saturn', keywords: ['спокуса','залежність','тінь'], keywordsEn: ['temptation','addiction','shadow'], positive: 'Пристрасть, харизма, матеріальний успіх. Диявол дає потужну енергію, харизму, магнетизм і здатність досягати матеріального успіху.', positiveEn: 'Passion, charisma, material success', negative: 'Залежності, маніпуляції, жадібність. У негативному прояві людина може потрапити у залежність від грошей, влади чи інших людей.', negativeEn: 'Addictions, manipulation, greed', advice: 'Усвідомлюйте свої тіньові сторони та звільняйтесь від залежностей. Ваша харизма — потужний інструмент, використовуйте його мудро.', adviceEn: 'Acknowledge your shadow side and free yourself from addictions', slug: 'chyslo-15' },
  { id: 16, name: 'Вежа', nameEn: 'The Tower', arcana: 'The Tower', planet: 'Марс', planetEn: 'Mars', keywords: ['руйнування','пробудження','звільнення'], keywordsEn: ['destruction','awakening','liberation'], positive: 'Раптове пробудження, звільнення, руйнування ілюзій. Вежа зносить все хибне та штучне, щоб звільнити місце для справжнього.', positiveEn: 'Sudden awakening, liberation, shattering of illusions', negative: 'Катастрофа, шок, конфлікти. У негативному прояві людина може притягувати кризи та руйнування в своє життя.', negativeEn: 'Catastrophe, shock, conflicts', advice: 'Приймайте раптові зміни як можливість для зростання. Після руйнування завжди приходить оновлення.', adviceEn: 'Embrace sudden changes as an opportunity for growth', slug: 'chyslo-16' },
  { id: 17, name: 'Зірка', nameEn: 'The Star', arcana: 'The Star', planet: 'Уран', planetEn: 'Uranus', keywords: ['надія','натхнення','зцілення'], keywordsEn: ['hope','inspiration','healing'], positive: 'Надія, натхнення, творчість, духовне зцілення. Зірка дарує світло надії навіть у найтемніші часи. Це енергія натхнення та цілительства.', positiveEn: 'Hope, inspiration, creativity, spiritual healing', negative: 'Відірваність від реальності, наївність. У негативному прояві людина може жити в мріях і уникати реальності.', negativeEn: 'Disconnection from reality', advice: 'Тримайте надію та вірте у свою зірку, слідуйте мрії. Ваша здатність надихати — ваш найбільший дар.', adviceEn: 'Hold on to hope and believe in your star, follow your dream', slug: 'chyslo-17' },
  { id: 18, name: 'Місяць', nameEn: 'The Moon', arcana: 'The Moon', planet: 'Місяць', planetEn: 'Moon', keywords: ['ілюзії','підсвідомість','тривога'], keywordsEn: ['illusions','subconscious','anxiety'], positive: 'Інтуїція, уява, глибоке підсвідоме знання. Місяць дарує потужну інтуїцію, багату уяву та зв\'язок з підсвідомим.', positiveEn: 'Intuition, imagination, deep subconscious knowledge', negative: 'Ілюзії, страхи, тривога, обман. У негативному прояві людина може страждати від тривоги, страхів та ілюзій.', negativeEn: 'Illusions, fears, anxiety', advice: 'Працюйте зі своїм підсвідомим та не піддавайтесь ілюзіям. Розвивайте інтуїцію через медитацію та роботу зі снами.', adviceEn: 'Work with your subconscious and do not succumb to illusions', slug: 'chyslo-18' },
  { id: 19, name: 'Сонце', nameEn: 'The Sun', arcana: 'The Sun', planet: 'Сонце', planetEn: 'Sun', keywords: ['радість','успіх','життєва сила'], keywordsEn: ['joy','success','vitality'], positive: 'Радість, успіх, оптимізм, щастя. Сонце — найпозитивніша енергія. Вона дарує радість, успіх, оптимізм та здатність освітлювати життя інших.', positiveEn: 'Joy, success, optimism, happiness', negative: 'Самовпевненість, поверховість, зарозумілість. У негативному прояві людина може стати занадто самовпевненою і поверховою.', negativeEn: 'Overconfidence, superficiality', advice: 'Сяйте як сонце — діліться радістю та енергією з іншими. Ваш оптимізм зцілює і надихає.', adviceEn: 'Shine like the sun — share joy and energy with others', slug: 'chyslo-19' },
  { id: 20, name: 'Суд', nameEn: 'Judgement', arcana: 'Judgement', planet: 'Плутон', planetEn: 'Pluto', keywords: ['відродження','призначення','заклик'], keywordsEn: ['rebirth','calling','awakening'], positive: 'Відродження, прийняття призначення, трансформація. Суд — це заклик до пробудження, усвідомлення свого справжнього призначення.', positiveEn: 'Rebirth, embracing your calling, transformation', negative: 'Самоосуд, невміння відпускати минуле. У негативному прояві людина може карати себе за минулі помилки і не рухатися вперед.', negativeEn: 'Self-judgment, inability to let go', advice: 'Прислухайтесь до внутрішнього заклику та приймайте своє призначення. Час простити минуле і почати нове.', adviceEn: 'Listen to your inner calling and embrace your destiny', slug: 'chyslo-20' },
  { id: 21, name: 'Світ', nameEn: 'The World', arcana: 'The World', planet: 'Сатурн', planetEn: 'Saturn', keywords: ['завершення','цілісність','досягнення'], keywordsEn: ['completion','wholeness','achievement'], positive: 'Завершеність, досягнення мети, гармонія. Світ — це вершина, цілісність, завершення великого циклу. Людина з цією енергією здатна бачити цілу картину.', positiveEn: 'Completion, goal achievement, harmony', negative: 'Стагнація, страх завершення, перфекціонізм. У негативному прояві людина може боятися завершень або застрягти в перфекціонізмі.', negativeEn: 'Stagnation, fear of completion', advice: 'Святкуйте свої досягнення та готуйтесь до нового циклу. Завершення — це не кінець, а вихід на новий рівень.', adviceEn: 'Celebrate your achievements and prepare for a new cycle', slug: 'chyslo-21' },
  { id: 22, name: 'Блазень', nameEn: 'The Fool', arcana: 'The Fool', planet: 'Уран', planetEn: 'Uranus', keywords: ['свобода','початок','довіра'], keywordsEn: ['freedom','beginning','trust'], positive: 'Свобода, нові початки, спонтанність. Блазень — енергія абсолютної свободи, безстрашності та готовності до стрибку в невідоме.', positiveEn: 'Freedom, new beginnings, spontaneity', negative: 'Безвідповідальність, хаос, інфантилізм. У негативному прояві людина може бути безвідповідальною і уникати дорослих рішень.', negativeEn: 'Irresponsibility, chaos', advice: 'Будьте відкриті до нового і довіряйте процесу життя. Іноді потрібно просто стрибнути — і крила розкриються у польоті.', adviceEn: 'Be open to the new and trust the process of life', slug: 'chyslo-22' },
];

export const getEnergyById = (id: number): Energy | undefined =>
  ENERGIES.find(e => e.id === id);

export const getEnergyBySlug = (slug: string): Energy | undefined =>
  ENERGIES.find(e => e.slug === slug);
