// Fallback static data — used as initial store state when Supabase is not yet configured
// or when the device is offline. Mirrors the seed data in 001_initial_schema.sql.

import type { Energy } from '@/constants/energies';

export const FALLBACK_ENERGIES: Energy[] = [
  { id: 1,  name: 'Маг',               arcana: 'The Magician',      planet: 'Меркурій', planetEn: 'Mercury', keywords: ['воля','майстерність','ініціатива'], keywordsEn: ['willpower','mastery','initiative'], positive: 'Лідерство, впевненість, здатність досягати цілей', positiveEn: 'Leadership, confidence, ability to achieve goals', negative: 'Маніпуляції, егоїзм, хитрість', negativeEn: 'Manipulation, egoism, cunning', advice: 'Розвивайте свої таланти та використовуйте силу волі для досягнення цілей', adviceEn: 'Develop your talents and use willpower to achieve your goals' },
  { id: 2,  name: 'Жриця',             arcana: 'The High Priestess', planet: 'Місяць', planetEn: 'Moon', keywords: ['інтуїція','мудрість','таємниця'], keywordsEn: ['intuition','wisdom','mystery'], positive: 'Глибока інтуїція, мудрість, чутливість', positiveEn: 'Deep intuition, wisdom, sensitivity', negative: 'Замкненість, пасивність', negativeEn: 'Withdrawal, passivity', advice: 'Довіряйте своїй інтуїції та розвивайте внутрішню мудрість', adviceEn: 'Trust your intuition and cultivate inner wisdom' },
  { id: 3,  name: 'Імператриця',       arcana: 'The Empress',        planet: 'Венера', planetEn: 'Venus', keywords: ['творчість','достаток','краса'], keywordsEn: ['creativity','abundance','beauty'], positive: 'Творчість, материнство, достаток, гармонія', positiveEn: 'Creativity, nurturing, abundance, harmony', negative: 'Лінь, залежність від комфорту', negativeEn: 'Laziness, dependence on comfort', advice: 'Розкривайте свій творчий потенціал та створюйте красу навколо себе', adviceEn: 'Unlock your creative potential and create beauty around you' },
  { id: 4,  name: 'Імператор',         arcana: 'The Emperor',        planet: 'Марс', planetEn: 'Mars', keywords: ['влада','структура','стабільність'], keywordsEn: ['authority','structure','stability'], positive: 'Стабільність, відповідальність, організованість', positiveEn: 'Stability, responsibility, organization', negative: 'Тиранія, жорсткість, контроль', negativeEn: 'Tyranny, rigidity, control', advice: 'Будуйте структуру та порядок у житті, беріть відповідальність', adviceEn: 'Build structure and order in your life, take responsibility' },
  { id: 5,  name: 'Ієрофант',          arcana: 'The Hierophant',     planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['вчитель','традиції','духовність'], keywordsEn: ['teacher','tradition','spirituality'], positive: 'Мудрість, наставництво, духовний розвиток', positiveEn: 'Wisdom, mentorship, spiritual growth', negative: 'Догматизм, моралізаторство', negativeEn: 'Dogmatism, moralizing', advice: 'Шукайте знання та діліться мудрістю з іншими', adviceEn: 'Seek knowledge and share wisdom with others' },
  { id: 6,  name: 'Закохані',          arcana: 'The Lovers',         planet: 'Венера', planetEn: 'Venus', keywords: ['любов','вибір','гармонія'], keywordsEn: ['love','choice','harmony'], positive: 'Любов, гармонія у стосунках, правильний вибір', positiveEn: 'Love, harmony in relationships, right choice', negative: 'Нерішучість, залежність', negativeEn: 'Indecisiveness, dependency', advice: 'Приймайте рішення серцем, будуйте гармонійні стосунки', adviceEn: 'Make decisions with your heart, build harmonious relationships' },
  { id: 7,  name: 'Колісниця',         arcana: 'The Chariot',        planet: 'Марс', planetEn: 'Mars', keywords: ['перемога','рух','амбіції'], keywordsEn: ['victory','movement','ambition'], positive: 'Перемога, рух вперед, сила волі, успіх', positiveEn: 'Victory, moving forward, willpower, success', negative: 'Агресія, нетерпіння', negativeEn: 'Aggression, impatience', advice: 'Рухайтесь до мети з рішучістю, контролюйте свої імпульси', adviceEn: 'Move toward your goal with determination, control your impulses' },
  { id: 8,  name: 'Справедливість',    arcana: 'Justice',            planet: 'Сатурн', planetEn: 'Saturn', keywords: ['баланс','карма','закон'], keywordsEn: ['balance','karma','law'], positive: 'Справедливість, баланс, чесність', positiveEn: 'Justice, balance, honesty', negative: 'Осудливість, надмірна критичність', negativeEn: 'Judgmentalism, excessive criticism', advice: 'Дотримуйтесь балансу та будьте чесні з собою і іншими', adviceEn: 'Maintain balance and be honest with yourself and others' },
  { id: 9,  name: 'Відлюдник',         arcana: 'The Hermit',         planet: 'Нептун', planetEn: 'Neptune', keywords: ['самопізнання','мудрість','самотність'], keywordsEn: ['self-discovery','wisdom','solitude'], positive: 'Глибоке самопізнання, мудрість, духовний пошук', positiveEn: 'Deep self-discovery, wisdom, spiritual quest', negative: 'Ізоляція, відчуженість', negativeEn: 'Isolation, alienation', advice: 'Знаходьте час для самопізнання та внутрішнього розвитку', adviceEn: 'Find time for self-discovery and inner growth' },
  { id: 10, name: 'Колесо Фортуни',    arcana: 'Wheel of Fortune',   planet: 'Юпітер', planetEn: 'Jupiter', keywords: ['доля','цикли','удача'], keywordsEn: ['destiny','cycles','luck'], positive: 'Удача, нові можливості, позитивні зміни', positiveEn: 'Luck, new opportunities, positive changes', negative: 'Непостійність, фаталізм', negativeEn: 'Instability, fatalism', advice: 'Приймайте зміни як частину життя та використовуйте можливості', adviceEn: 'Embrace change as part of life and seize opportunities' },
  { id: 11, name: 'Сила',              arcana: 'Strength',           planet: 'Сонце', planetEn: 'Sun', keywords: ['мужність','терпіння','внутрішня сила'], keywordsEn: ['courage','patience','inner strength'], positive: 'Внутрішня сила, мужність, терпіння, стійкість', positiveEn: 'Inner strength, courage, patience, resilience', negative: 'Слабкість, страхи', negativeEn: 'Weakness, fears', advice: 'Розвивайте внутрішню силу та мужність через терпіння', adviceEn: 'Develop inner strength and courage through patience' },
  { id: 12, name: 'Повішений',         arcana: 'The Hanged Man',     planet: 'Нептун', planetEn: 'Neptune', keywords: ['жертва','пауза','новий погляд'], keywordsEn: ['sacrifice','pause','new perspective'], positive: 'Нові перспективи, жертовність, духовне переродження', positiveEn: 'New perspectives, sacrifice, spiritual rebirth', negative: 'Застій, пасивність', negativeEn: 'Stagnation, passivity', advice: 'Іноді потрібно зупинитися щоб побачити нові можливості', adviceEn: 'Sometimes you need to pause to see new possibilities' },
  { id: 13, name: 'Смерть',            arcana: 'Death',              planet: 'Плутон', planetEn: 'Pluto', keywords: ['трансформація','завершення','оновлення'], keywordsEn: ['transformation','endings','renewal'], positive: 'Трансформація, оновлення, звільнення від старого', positiveEn: 'Transformation, renewal, release from the old', negative: 'Страх змін, болісні закінчення', negativeEn: 'Fear of change, painful endings', advice: 'Приймайте завершення як початок нового етапу', adviceEn: 'Accept endings as the beginning of a new chapter' },
  { id: 14, name: 'Помірність',        arcana: 'Temperance',         planet: 'Сатурн', planetEn: 'Saturn', keywords: ['гармонія','терпіння','баланс'], keywordsEn: ['harmony','patience','balance'], positive: 'Гармонія, помірність, терпіння, баланс', positiveEn: 'Harmony, temperance, patience, balance', negative: 'Надмірна стриманість', negativeEn: 'Excessive restraint', advice: 'Знаходьте золоту середину та будьте терплячі', adviceEn: 'Find the golden mean and be patient' },
  { id: 15, name: 'Диявол',            arcana: 'The Devil',          planet: 'Сатурн', planetEn: 'Saturn', keywords: ['спокуса','залежність','тінь'], keywordsEn: ['temptation','addiction','shadow'], positive: 'Пристрасть, харизма, матеріальний успіх', positiveEn: 'Passion, charisma, material success', negative: 'Залежності, маніпуляції, жадібність', negativeEn: 'Addictions, manipulation, greed', advice: 'Усвідомлюйте свої тіньові сторони та звільняйтесь від залежностей', adviceEn: 'Acknowledge your shadow side and free yourself from addictions' },
  { id: 16, name: 'Вежа',              arcana: 'The Tower',          planet: 'Марс', planetEn: 'Mars', keywords: ['руйнування','пробудження','звільнення'], keywordsEn: ['destruction','awakening','liberation'], positive: 'Раптове пробудження, звільнення, руйнування ілюзій', positiveEn: 'Sudden awakening, liberation, shattering of illusions', negative: 'Катастрофа, шок, конфлікти', negativeEn: 'Catastrophe, shock, conflicts', advice: 'Приймайте раптові зміни як можливість для зростання', adviceEn: 'Embrace sudden changes as an opportunity for growth' },
  { id: 17, name: 'Зірка',             arcana: 'The Star',           planet: 'Уран', planetEn: 'Uranus', keywords: ['надія','натхнення','зцілення'], keywordsEn: ['hope','inspiration','healing'], positive: 'Надія, натхнення, творчість, духовне зцілення', positiveEn: 'Hope, inspiration, creativity, spiritual healing', negative: 'Відірваність від реальності', negativeEn: 'Disconnection from reality', advice: 'Тримайте надію та вірте у свою зірку, слідуйте мрії', adviceEn: 'Hold on to hope and believe in your star, follow your dream' },
  { id: 18, name: 'Місяць',            arcana: 'The Moon',           planet: 'Місяць', planetEn: 'Moon', keywords: ['ілюзії','підсвідомість','тривога'], keywordsEn: ['illusions','subconscious','anxiety'], positive: 'Інтуїція, уява, глибоке підсвідоме знання', positiveEn: 'Intuition, imagination, deep subconscious knowledge', negative: 'Ілюзії, страхи, тривога', negativeEn: 'Illusions, fears, anxiety', advice: 'Працюйте зі своїм підсвідомим та не піддавайтесь ілюзіям', adviceEn: 'Work with your subconscious and do not succumb to illusions' },
  { id: 19, name: 'Сонце',             arcana: 'The Sun',            planet: 'Сонце', planetEn: 'Sun', keywords: ['радість','успіх','життєва сила'], keywordsEn: ['joy','success','vitality'], positive: 'Радість, успіх, оптимізм, щастя', positiveEn: 'Joy, success, optimism, happiness', negative: 'Самовпевненість, поверховість', negativeEn: 'Overconfidence, superficiality', advice: 'Сяйте як сонце — діліться радістю та енергією з іншими', adviceEn: 'Shine like the sun — share joy and energy with others' },
  { id: 20, name: 'Суд',               arcana: 'Judgement',          planet: 'Плутон', planetEn: 'Pluto', keywords: ['відродження','призначення','заклик'], keywordsEn: ['rebirth','calling','awakening'], positive: 'Відродження, прийняття призначення, трансформація', positiveEn: 'Rebirth, embracing your calling, transformation', negative: 'Самоосуд, невміння відпускати', negativeEn: 'Self-judgment, inability to let go', advice: 'Прислухайтесь до внутрішнього заклику та приймайте своє призначення', adviceEn: 'Listen to your inner calling and embrace your destiny' },
  { id: 21, name: 'Світ',              arcana: 'The World',          planet: 'Сатурн', planetEn: 'Saturn', keywords: ['завершення','цілісність','досягнення'], keywordsEn: ['completion','wholeness','achievement'], positive: 'Завершеність, досягнення мети, гармонія', positiveEn: 'Completion, goal achievement, harmony', negative: 'Стагнація, страх завершення', negativeEn: 'Stagnation, fear of completion', advice: 'Святкуйте свої досягнення та готуйтесь до нового циклу', adviceEn: 'Celebrate your achievements and prepare for a new cycle' },
  { id: 22, name: 'Блазень',           arcana: 'The Fool',           planet: 'Уран', planetEn: 'Uranus', keywords: ['свобода','початок','довіра'], keywordsEn: ['freedom','beginning','trust'], positive: 'Свобода, нові початки, спонтанність', positiveEn: 'Freedom, new beginnings, spontaneity', negative: 'Безвідповідальність, хаос', negativeEn: 'Irresponsibility, chaos', advice: 'Будьте відкриті до нового і довіряйте процесу життя', adviceEn: 'Be open to the new and trust the process of life' },
];
